version: "3.8"

networks:
  ob_submitter-network:
    driver: bridge

services:
  submitter:
    build: ./
    command: /app/submitter
    env_file:
      - ./.env
    volumes:
      - "./db:/app/db"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: always
    networks:
      - ob_submitter-network

  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/log:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
    networks:
      - ob_submitter-network
